from . import fleet_vehicle
from . import insurance_type
from . import sale_order
from . import product
from . import sale_order_line
from . import car_rental_contract
from . import fleet_vehicle_model
from . import res_partner
from . import crm_lead
from . import vehicle_reservation
from . import fleet_service
from . import return_wizard
from . import extra_km
from . import mail_mail
from . import insurance_refund_wizard
from . import owner_statement
from . import owner_statement_report
from . import vehicle_statement
from . import fleet_odometer
