from . import fleet_vehicle
from . import insurance_type
from . import sale_order
from . import product
from . import sale_order_line
from . import car_rental_contract
from . import fleet_vehicle_model
from . import res_partner
from . import crm_lead
from . import vehicle_reservation