{
    'name': 'Vehicle Custom Fields',
    'version': '19.0.1.0.0',
    'category': 'Fleet',
    'summary': 'Add custom fields to Fleet Vehicle',
    'depends': ['fleet','sale','fleet_rental','crm'],
    'data': [
    'views/fleet_vehicle_views.xml',
    'security/ir.model.access.csv',
    'views/sale_order_views.xml',
    'reports/sale_order_report.xml',
    'views/product_views.xml',
    'views/car_rental_contract_views.xml',
    'reports/rental_contract_report.xml',
    'reports/insurance_policy_report.xml',
    'reports/customer_settlement_report.xml',
    'views/fleet_vehicle_model_views.xml',
    'views/res_partner_views.xml',
    'views/crm_lead_views.xml',
    'views/fleet_management_views.xml',
    'views/fleet_service_views.xml',
    'reports/service_report.xml',
    'views/contract_sequences.xml',
    'views/return_wizard_views.xml',
    'views/extra_km_views.xml',
    'views/insurance_refund_wizard_views.xml',
    'views/owner_statement_views.xml',
    'views/owner_statement_sequence.xml',
    'views/owner_statement_report_views.xml',
    'reports/owner_statement_report_pdf.xml',
    'reports/owner_statement_lines_pdf.xml',
],
    'installable': True,
    'auto_install': False,
}